apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-staging-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/KeremAR/Homelab-Infrastructure.git
    targetRevision: main
    path: 4-Deploy-App/helm/frontend
    helm:
      releaseName: staging-frontend
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
