apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-production-user-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/KeremAR/Homelab-Infrastructure.git
    targetRevision: main
    path: 6-Helm-Deploy/user-service
    helm:
      releaseName: production-user-service
      valueFiles:
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
