apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-todo-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/KeremAR/Homelab-Infrastructure.git
    targetRevision: main
    path: 4-Deploy-App/kubectl/production/todo-service/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
